parameters:
    domnikl_statsd.service.class: Domnikl\StatsdBundle\Service\Client

services:
    domnikl_statsd:
        class: %domnikl_statsd.service.class%
        arguments:
            - %domnikl_statsd.connection.class%
            - %domnikl_statsd.namespace%
            - %domnikl_statsd.connection.options%

    statsd:
        alias: domnikl_statsd
